# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    always_put_control_body_on_new_line: false
    avoid_print: false
    lines_longer_than_80_chars: false
    prefer_single_quotes: true
    require_trailing_commas: false
